CREATE TABLE IF NOT EXISTS kis_access_token_cache (
    id BIGSERIAL PRIMARY KEY,
    mode VARCHAR(16) NOT NULL UNIQUE,
    token VARCHAR(2048) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

